name: C# CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Adjust this to your project's .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Adjust this to your project's .NET version

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Format code
      run: dotnet format --verify-no-changes

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Adjust this to your project's .NET version

    - name: Install dotnet-roslynator
      run: dotnet tool install -g roslynator.dotnet.cli

    - name: Run Roslynator
      run: |
        roslynator analyze ScanMail.sln \
          --exclude "**/*Test*/**/*.cs" "**/*Tests*/**/*.cs" "**/obj/**" "**/bin/**" \
          --output roslynator-report.xml \
          --verbosity d

    - name: Check if report exists
      run: |
        if [ -f roslynator-report.xml ]; then
          echo "Roslynator report generated successfully."
        else
          echo "Roslynator report not found. Listing directory contents:"
          ls -la
          exit 1
        fi
    - name: Upload Roslynator report
      uses: actions/upload-artifact@v4
      with:
        name: roslynator-report
        path: roslynator-report.xml
      if: always()
